version: "3"

services:
 canary:
      container_name: opencanary
      restart: unless-stopped
      volumes:
          # - ./opencanary/:/etc/opencanaryd/
          # - ./data/:/root/
          - ./opencanary.conf:/etc/opencanaryd/opencanary.conf
      ports:
              - '21:21'
              - '888:80'
      image: 'opencanary'
      build:
        context: .
        dockerfile: Dockerfile.latest
      command: opencanaryd --dev
