
x-common: &common
  restart: unless-stopped
  tmpfs:
    - /run
  volumes:
    - ./data/.opencanary.conf:/root/.opencanary.conf
    # uncomment below if running Samba
    # - audit-log:/var/log/samba
  image: "opencanary"
  network_mode: "host"
  ports:
    # Comment/un-comment the port lines below to disable/enable the services you are using
    # FTP
    - "21:21"
    # SSH
    # - "22:22"
    # Telnet
    # - "23:23"
    # TFTP
    # - "69:69"
    # HTTP
    - "80:80"
    # NTP
    # - "123:123"
    # SNMP
    # - "161:161"
    # MSSQL
    # - "1433:1433"
    # MYSQL
    # - "3306:3306"
    # RDP
    # - "3389:3389"
    # VNC
    # - "5000:5000"
    # SIP
    # - "5060:5060"
    # REDIS
    # - "6379:6379"
    # TCP Banner
    # - "8001:8001"
    # HTTP Proxy
    # - "8080:8080"
    # Git
    # - "9418:9418"

services:
  latest: # docker compose up --build -d latest
    <<: *common
    container_name: opencanary_latest
    image: thinkst/opencanary
    build:
      context: .
      dockerfile: Dockerfile.latest

  # Uncomment if smb is to be enabled
  # samba: # docker compose up --build -d samba
  #   <<: *common
  #   container_name: opencanary_samba
  #   image: thinkst/opencanary_samba
  #   restart: unless-stopped
  #   volumes:
  #     - audit-log:/var/log/samba/
  #     - ./data/smb.conf:/etc/samba/smb.conf
  #   network_mode: host
  #   ports:
  #     # SMB
  #     - "445:445"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.smb

  stable: # docker compose up --build -d stable
    <<: *common
    container_name: opencanary_stable
    build:
      context: .
      dockerfile: Dockerfile.stable

volumes:
  audit-log: